services:
  property_db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=property_app_mysql'
      - 'MYSQL_PASSWORD=12345678'
      - 'MYSQL_ROOT_PASSWORD=12345678'
    ports:
      - '33061:3306/tcp'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - property_db:/var/lib/mysql/
  user_db:
      image: 'mysql:latest'
      environment:
        - 'MYSQL_DATABASE=user_app_mysql'
        - 'MYSQL_PASSWORD=12345678'
        - 'MYSQL_ROOT_PASSWORD=12345678'
      ports:
        - '33062:3306/tcp'
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
      volumes:
        - user_db:/var/lib/mysql/

  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: 'rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=user'
      - 'RABBITMQ_DEFAULT_PASS=1'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      timeout: 20s
      retries: 10
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

volumes:
  property_db:
  user_db:
  rabbitmq: